version: "3"
services:
  electrum-dev:
    build:
      context: .
      dockerfile: "docker/electrom-cash.dockerfile"
    environment:
      - ELECTRUM_USER=electrumgithub
      - ELECTRUM_PASSWORD=electrumgithubpassword
      - TESTNET=true
      - WALLET=/data/wallet_de_pruebas
    volumes:
      - ./docker/electrum:/data
    ports:
      - "127.0.0.1:8000:8000"
    entrypoint: sh -c "/data/electrum-entrypoint.sh"
