version: "3"
services:
  postgres-dev:
    image: "postgres:alpine"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./_executions-data/postgres:/var/lib/postgresql/data
  electrum-dev:
    build:
      context: .
      dockerfile: "docker/electrom-cash.dockerfile"
    environment:
      - ELECTRUM_USER=electrum
      - ELECTRUM_PASSWORD=electrumpassword
      - TESTNET=true
      - WALLET=/data/wallet_de_pruebas
    volumes:
      - ./docker/electrum:/data
    ports:
      - "127.0.0.1:8000:8000"
    entrypoint: sh -c "/data/electrum-entrypoint.sh"
